###Main Page###
Party_EnquireUser_UserID_TextBox = '//input[contains(@id,"userDetail:UserID")]'
Party_EnquireUser_Search_Button = '//input[contains(@name,"Search")]'
Party_EnquireUser_GivenName_TextBox = '//input[contains(@name,"userDetail:UserName")]'
Party_EnquireUser_Surname_TextBox = '//input[contains(@name,"userDetail:Surname")]'
Party_EnquireUser_Title_TextBox = '//input[contains(@name,"userDetail:Title")]'
Party_EnquireUser_OSUserID_TextBox = '//input[contains(@name,"userDetail:OSUserID")]'
Party_EnquireUser_Country_Dropdown = '//input[contains(@id,"userDetail:CountryLocale")]'
Party_EnquireUser_UserType_Dropdown = '//input[contains(@id,"userDetail:UserType")]'
Party_EnquireUser_Language_Dropdown = '//input[contains(@id,"userDetail:LanguageLocale")]'
Party_EnquireUser_DefaultZone_Dropdown = '//input[contains(@id,"userDetail:Zone")]'
Party_EnquireUser_BranchName_Dropdown = '//input[contains(@id,"userDetail:BranchSortCode")]'
Party_EnquireUser_Phone_Dropdown = '//input[contains(@name,"userDetail:Phone")]'
Party_EnquireUser_Email_Dropdown = '//input[contains(@name,"userDetail:Email")]'
Party_EnquireUser_AssocZone_TableGrid_Row = '//div[contains(@id,"assignedZoneList")]//div[contains(@class,"GridView")]//div[@role="row"]'
TableGrid_RowValues_Zone = '//td[@role="gridcell" and @idx="0"]'
TableGrid_RowValues_Branch = '//td[@role="gridcell" and @idx="1"]'
Party_EnquireUser_AssocRoles_TableGrid_Row = '//div[contains(@id,"assignedRoleList")]//div[contains(@class,"GridView")]//div[@role="row"]'
TableGrid_RowValues_Role = '//td[@role="gridcell" and @idx="0"]'
Party_HelpMenu_Button  =   '//span[@widgetid="uxpHelpMenu"]//span[@class="dijitReset dijitInline dijitArrowButtonInner"]'
Party_LogOut_Button  =   '//div[@aria-label="uxpUserHelpList"]//tr[@widgetid="logoutButton"]'

###Search User dialog###
Party_SearchUser_UserID_TextBox = '//td[@class="ux-layoutContainer"]//input[contains(@name,"userName")]'
Party_SearchUser_Search_Button = '//span[text()="Search User"]//parent::div//following::div//input[contains(@name,"Search")]'
Party_SearchUser_Next_Button = '//div[@role="dialog"]//input[contains(@name,"Next")]'
Party_SearchUser_Table = '//div[@role="dialog"]//div[contains(@id,"grid__View")]//div[@role="row"]'
Party_SearchUser_TableRow = '//div[@role="dialog"]//div[contains(@id,"grid__View")]//tr'
Party_SearchUser_UserType_TableRow = '//td[@role="gridcell" and @idx="2"]'
Party_SearchUser_UserCountry_TableRow = '//td[@role="gridcell" and @idx="3"]'
Party_SearchUser_UserID_TableRow = '//td[@role="gridcell" and @idx="1"]'
Party_SearchUser_RadioButton_Col = '//td[@role="gridcell" and @idx="0"]/div[@role="radio"]'
Party_SearchUser_Error_TextMessage = '//div[@role="dialog"]//input[@uitype="ValueLabel" and contains(@name,"msg")]'
Party_SearchUser_Close_Dialog = '//span[@title="Cancel" and contains(@class,"DialogCloseIcon")]'
