### Party Details Enquire  - Party Details Page ###
Party_EnquirePartyDetails_PartyDetails_PartyId_Textbox = '//input[contains(@id,"PartyID") and not(contains(@id, "OffScreen"))]'

### Party Details Enquire - Search Party Page ###
Party_EnquirePartyDetails_EnterpriseParty_RelatedItems_Menu = '//span[contains(@id, "relatedItems") and contains(text(),"Related Items")]'
Party_EnquirePartyDetails_EnterpriseParty_Addresses_MenuItem = '//td[contains(@id, "Addresses") and contains(text(),"Addresses")]'

### Party Details Enquire - Search Party details ###
Party_EnquirePartyDetails_Locality_Textbox = '//input[contains(@id,"locality") and not(contains(@id, "OffScreen"))]'
Party_EnquirePartyDetails_Entity_Textbox = '//input[contains(@id,"location")]'
Party_EnquirePartyDetails_PartyId_Textbox = '//input[contains(@id,"partyId") and not(contains(@id, "OffScreen"))]' 
Party_EnquirePartyDetails_EnterpriseName_Textbox = '//input[contains(@id,"name") and not(contains(@id, "OffScreen"))]'
Party_EnquirePartyDetails_CountryOfRegistration_Textbox = '//input[contains(@id,"regCountry")]'
Party_EnquirePartyDetails_CountryOfTaxDomicile_Textbox = '//input[contains(@id, "taxCountry")]'
Party_EnquirePartyDetails_ShortName_Textbox = '//input[contains(@id,"shortName") and not(contains(@id, "OffScreen"))]'  
Party_EnquirePartyDetails_AssignedBranch_Textbox = '//input[contains (@name, "03AssignedBranch")]'
Party_EnquirePartyDetails_PartySubType_Textbox = '//input[contains (@name, "03PartySubeType")]'
Party_EnquirePartyDetails_PartyCategory_Textbox = '//input[contains (@name, "03PartyCategory")]'
Party_EnquirePartyDetails_Registernumber_Textbox = '//input[contains (@name, "03ReadEntPartyBasicDtlsRs:readEntPartyBasicDtlsOutput:entPtyBasicDtls:regNumber")]'
Party_EnquirePartyDetails_Country_Textbox = '//td[@role="gridcell" and @idx="0"]'
Party_EnquirePartyDetails_Partytype_Textbox = '//input[contains (@name, "03PartyType")]'
Party_EnquirePartyDetails_Country_TableGrid_Row = '//div[contains(@id,"_HiddenVector_ReadEntPartyBasicDtlsRs")]//div[contains(@class,"GridView")]//div[@role="row"]//td[@role="gridcell" and @idx="0"]'
Party_EnquirePartyDetails_GoodsServiceTaxNumber_TableGrid_Row = '//div[contains(@id,"_HiddenVector_ReadEntPartyBasicDtlsRs")]//div[contains(@class,"GridView")]//div[@role="row"]//td[@role="gridcell" and @idx="1"]'
Party_EnquirePartyDetails_DateFormed_Textbox = '//input[contains(@id,"formationDt")]'
Party_EnquirePartyDetails_DateIncorporated_Textbox = '//input[contains(@id,"dateIncorporated")]'
Party_EnquirePartyDetails_DateCommencedTrading_Textbox = '//input[contains(@id,"tradeStDt")]'
Party_EnquirePartyDetails_AlternatePartyID_Textbox = '//input[contains(@id,"partyAlternativeId")]'
Party_EnquirePartyDetails_BusinessStatus_Textbox = '//input[contains(@id,"busStatus")]'
Party_EnquirePartyDetails_TaxExemptionStatus_Textbox = '//input[contains(@id,"partyTaxDtl:taxExemptId")]'
Party_EnquirePartyDetails_BeneficialOwners_Textbox = '//input[contains(@id,"noOfShareHolder")]'
Party_EnquirePartyDetails_Directors_Textbox = '//input[contains(@id,"numDirectors")]'
Party_EnquirePartyDetails_SIgnatories_Textbox = '//input[contains(@id,"numSignatories")]'
Party_EnquirePartyDetails_isParent_Textbox = '//input[contains(@id,"isParent")]'
Party_EnquirePartyDetails_ParentCountry_Textbox = '//input[contains(@id,"parentCountry")]'
Party_EnquirePartyDetails_NumberOfEmployees_Textbox = '//input[contains(@id,"noOfEmp")]'
Party_EnquirePartyDetails_CreditRatingAgency_Checkbox = '//input[contains(@id,"CreditRatingAgency")]'
Party_EnquirePartyDetails_isMemberGroup_Checkbox = '//input[contains(@id,"isMemberOfGroup")]'
Party_EnquirePartyDetails_AnnualTurnOverCurrency_Textbox = '//input[contains(@id,"annualTurnover:isoCurrency")]'
Party_EnquirePartyDetails_PriorYearTurnover_TextBox = '//input[contains(@id,"annualTurnover:amount")]'
Party_EnquirePartyDetails_ProjectedAnnualTurnover_Textbox = '//input[contains(@id,"prjTurnover:amount")]'
Party_EnquirePartyDetails_ManagerID_Textbox = '//input[contains(@id,"relationshipManager")]'
Party_EnquirePartyDetails_busActivity_Textbox = '//input[contains(@id,"busActivity")]'
Party_EnquirePartyDetails_TaxLiable_Textbox = '//input[contains(@id,"taxWhtLiable")]'
Party_EnquirePartyDetails_webURL_Textbox = '//input[contains(@id,"webURL")]'
Party_EnquirePartyDetails_TradingNames_Textbox = '//input[contains(@id,"businessType")]'
Party_EnquirePartyDetails_TradeNames_View_Button = '//td[contains(@class,"layoutContainer")]//input[contains(@onclick,"Enquire Trade Name Details")]'

### Party Address Dialog ###
Party_EnquirePartyDetails_PartyAddress_AddressType_Dropdown = '//input[contains (@id, "partyAddressSpecDetails:addressType")]'
Party_EnquirePartyDetails_PartyAddress_PostCode_Textbox = '//input[contains (@name, "03ListPartyAddrRs:listPartyAddressResponse:partyAddressDetailsList:partyAddressDetail:postCode")]'
Party_EnquirePartyDetails_PartyAddress_AddressLine1_Textbox = '//input[contains (@name, "03ListPartyAddrRs:listPartyAddressResponse:partyAddressDetailsList:partyAddressDetail:addressLine1")]'
Party_EnquirePartyDetails_PartyAddress_AddressLine2_Textbox = '//input[contains (@name, "03ListPartyAddrRs:listPartyAddressResponse:partyAddressDetailsList:partyAddressDetail:addressLine2")]'
Party_EnquirePartyDetails_PartyAddress_AddressLine3_Textbox = '//input[contains (@name, "03ListPartyAddrRs:listPartyAddressResponse:partyAddressDetailsList:partyAddressDetail:addressLine3")]'
Party_EnquirePartyDetails_PartyAddress_AddressLine4_Textbox = '//input[contains (@name, "03ListPartyAddrRs:listPartyAddressResponse:partyAddressDetailsList:partyAddressDetail:addressLine4")]'
Party_EnquirePartyDetails_PartyAddress_AddressCountry_Textbox = '//input[contains (@id, "partyAddressDetail:country")]'
Party_EnquirePartyDetails_PartyAddress_StateProvince_Dropdown = '//input[contains (@id, "partyAddressDetail:addressLine") and @type="combo"]'
Party_EnquirePartyDetails_PartyAddress_Town_Textbox = '//input[contains (@name, "03ListPartyAddrRs:listPartyAddressResponse:partyAddressDetailsList:partyAddressDetail:townOrCity")]'

###Business Activity Page###
Party_EnquirePartyDetails_BusinessActivity_Viewbutton = '//td[contains(@class,"ux-layoutContainer")]//input[contains(@onclick,"Enquire Enterprise Business Activity")]'
Party_EnquirePartyDetails_BusinessActivity_Country_Combobox = '//input[contains(@id, "businessActivityDtls:country")]'
Party_EnquirePartyDetails_BusinessActivity_Industrysector_Combobox = '//input[contains(@id, "businessActivityDtls:indust")]'
Party_EnquirePartyDetails_BusinessActivity_Combobox = '//input[contains(@id, "Dtls:businessActivity")]'
Party_EnquirePartyDetails_BusinessActivity_Is_Main_Activity_Checkbox = '//input[contains(@id, "isMainActivity")]'
Party_EnquirePartyDetails_BusinessActivity_Is_Primary_Activity_checkbox = '//input[contains(@id, "isPrimaryActivity")]'


 
