###Create User###
Party_CreateUser_UserId_TextBox = '//input[contains(@id,"UserDetail:UserID")]'
Party_CreateUser_GivenName_TextBox = '//input[contains(@id,"UserDetail:UserName")]'
Party_CreateUser_SurName_TextBox = '//input[contains(@id,"UserDetail:Surname")]'
Party_CreateUser_BusinessTitle_TextBox = '//input[contains(@id,"UserDetail:Title")]'
Party_CreateUser_OSUserID_TextBox = '//input[contains(@id,"UserDetail:OSUserID")]'
Party_CreateUser_CountryCode_TextBox = '//input[contains(@id,"UserDetail:CountryLocale")]'
Party_CreateUser_UserType_TextBox = '//input[contains(@id,"UserDetail:UserType")]'
Party_CreateUser_LocalVariant_TextBox = '//input[contains(@id,"UserDetail:UserType")]'
Party_CreateUser_LanguageCode_TextBox = '//input[contains(@id,"UserDetail:LanguageLocale")]'
Party_CreateUser_Email_TextBox = '//input[contains(@id,"UserDetail:Email")]'
Party_CreateUser_Phone_TextBox = '//input[contains(@id,"UserDetail:Phone")]'
Party_CreateUser_DefaultZone_TextBox = '//input[contains(@id,"UserDetail:Zone")]'
Party_CreateUser_BranchName_TextBox = '//input[contains(@id,"UserDetail:BranchSortCode")]'
Party_CreateUser_LocalVariant_TextBox = '//input[contains(@id,"UserDetail:UserType")]'
Party_CreateUser_Next_Button = '//input[contains(@id,"Next")]'
Party_CreateUser_Message_Text = '//input[contains(@id,"ShowMessage")]'

Party_CreateUser_Roles_Table = '//div[@role="presentation"]//div[contains(@id,"dojox_grid__View_3")]//div[@role="row"]'
Party_CreateUser_RoleName_TableRow = '//td[@role="gridcell" and @idx="1"]'
Party_CreateUser_Role_CheckBox = '//td[@role="gridcell" and @idx="0"]'
Party_CreateUser_Role_SelectAll = '//div[@role="presentation"]//div[contains(@aria-label,"Select all")]'

###Amend User###
Party_AmendUser_UserId_TextBox = '//input[contains(@id,"userDetail:UserID")]'
Party_AmendUser_GivenName_TextBox = '//input[contains(@id,"userDetail:UserName")]'
Party_AmendUser_SurName_TextBox = '//input[contains(@id,"userDetail:Surname")]'
Party_AmendUser_BusinessTitle_TextBox = '//input[contains(@id,"userDetail:Title")]'
Party_AmendUser_OSUserID_TextBox = '//input[contains(@id,"userDetail:OSUserID")]'
Party_AmendUser_CountryCode_TextBox = '//input[contains(@id,"userDetail:CountryLocale")]'
Party_AmendUser_UserType_TextBox = '//input[contains(@id,"userDetail:UserType")]'
Party_AmendUser_LocalVariant_TextBox = '//input[contains(@id,"userDetail:UserType")]'
Party_AmendUser_LanguageCode_TextBox = '//input[contains(@id,"userDetail:LanguageLocale")]'
Party_AmendUser_Email_TextBox = '//input[contains(@id,"userDetail:Email")]'
Party_AmendUser_Phone_TextBox = '//input[contains(@id,"userDetail:Phone")]'
Party_AmendUser_DefaultZone_TextBox = '//input[contains(@id,"userDetail:Zone")]'
Party_AmendUser_BranchName_TextBox = '//input[contains(@id,"userDetail:BranchSortCode")]'
Party_AmendUser_LocalVariant_TextBox = '//input[contains(@id,"userDetail:UserType")]'
Party_AmendUser_Next_Button = '//input[contains(@id,"Next")]'
Party_AmendUser_Message_Text = '//input[contains(@id,"ShowMessage")]'
Party_AmendUser_SearchUser_Dialog_TitleBar = '//span[contains(text(),"Search User")]'
Party_AmendUser_Remove_Zone_Locator = '//td[contains(text(), "${sZone}")]/preceding-sibling::td[contains(@role, "gridcell")]//div[contains(@id, "assignedZoneList")]'
Party_AmendUser_Remove_Row_Button = '//button[contains(@id,"removeRowassignedZoneList")]'
Party_AmendUser_New_Row_Button = '//button[contains(@id,"addRowassignedZoneList")]'
Party_AmendUser_Save_Row_Button = '//button[contains(@id,"saveRowassignedZoneList")]'
Party_AmendUser_New_Zone_TextBox = '//input[contains(@id,"assignedZoneListZONE")]'
Party_AmendUser_New_BranchName_TextBox = '//input[contains(@id,"assignedZoneListBRANCHSORTCODE")]'
Party_AmendUser_Zone_Menu_Item = '//div[contains(@id,"zone") and contains(text(), "${sZone}")]'
