###Repayment Paper Clip Notebook#####
LIQ_Repayment_Window = 'JavaWindow("title:=.*Repayment for.*","displayed:=1")'
LIQ_Repayment_Tab = 'JavaWindow("title:=.*Repayment for.*").JavaTab("tagname:=TabFolder")'
LIQ_Repayment_Options_Cashflow = 'JavaWindow("title:=.* Repayment.*").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'
LIQ_Repayment_Transactions_JavaTree = 'JavaWindow("title:=.*Repayment for.*").JavaTree("attached text:=Drill down to Edit")'
LIQ_Repayment_Add_Button = 'JavaWindow("title:=.*Repayment for.*").JavaButton("attached text:=Add")'
LIQ_Repayment_Delete_Button = 'JavaWindow("title:=.*Repayment for.*").JavaButton("attached text:=Delete")'
LIQ_Repayment_EffectiveDate_Textfield = 'JavaWindow("title:=.*Repayment for.*").JavaEdit("attached text:=AUD", "labeled_containers_path:=Tab:General;")'
LIQ_Repayment_Options_ChangeEffectiveDate = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=Options").JavaMenu("label:=Change Effective Date")'
LIQ_Repayment_EnterNewEffectiveDate_Textfield = 'JavaWindow("title:=Enter New Effective Date").JavaEdit("tagname:=Text")'
LIQ_Repayment_EnterNewEffectiveDate_OK_Button = 'JavaWindow("title:=Enter New Effective Date").JavaButton("attached text:=OK")'
LIQ_Repayment_WorkflowItems = 'JavaWindow("title:=.*Repayment for.*").JavaTree("attached text:=.*Workflow .*")'
LIQ_Repayment_AwaitingApproval_Status_Window = 'JavaWindow("title:=Awaiting Approval Repayment.*")'
LIQ_Repayment_Released_Status_Window = 'JavaWindow("title:=Released Repayment .*")'
LIQ_Repayment_Save_Menu = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_Repayment_ChangeEffectiveDate_Menu = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=Options").JavaMenu("label:=Change Effective Date")'
LIQ_Repayment_TransactionDescription_Textfield = 'JavaWindow("title:=.*Repayment for.*").JavaEdit("labeled_containers_path:=Tab:General;Group:Transaction Description:;")'
LIQ_Repayment_Amount = 'JavaWindow("title:=.*Repayment for.*").JavaEdit("attached text:=Amount:")'
LIQ_Repayment_File_Save = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_Repayment_GLEntries_Menu = 'JavaWindow("title:=Released Repayment.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'

LIQ_PendingRepayment_EffectiveDate_Textfield = 'JavaWindow("title:=Enter New Effective Date").JavaEdit("tagname:=Text")'
LIQ_PendingRepayment_EffectiveDate_Ok_Button = 'JavaWindow("title:=Enter New Effective Date").JavaButton("attached text:=OK")'
LIQ_FeesandOutstandings_Window = 'JavaWindow("title:=Fees and Outstandings")'
LIQ_FeesandOutstandings_JavaTree = 'JavaWindow("title:=Fees and Outstandings").JavaTree("attached text:=Select a Fee or Outstanding and then add new transactions")'
LIQ_FeesandOutstandings_Upper_JavaTree = 'JavaWindow("title:=Fees and Outstandings").JavaTree("attached text:=Select a Fee or Outstanding and then add new transactions")'
LIQ_FeesandOutstandings_NewTransactions_JavaTree = 'JavaWindow("title:=Fees and Outstandings").JavaTree("labeled_containers_path:=Group:New Transactions;")'
LIQ_FeesandOutstandings_FreeFormEventFee_RadioButton = 'JavaWindow("title:=Fees and Outstandings").JavaRadioButton("attached text:=Freeform Event Fee")'
LIQ_FeesandOutstandings_Add_Button = 'JavaWindow("title:=Fees and Outstandings").JavaButton("attached text:=Add")'
LIQ_FeesandOutstandings_OK_Button = 'JavaWindow("title:=Fees and Outstandings").JavaButton("attached text:=OK")'

LIQ_Fee_Window = 'JavaWindow("title:=.* Fee .*")'
LIQ_Fee_RequestedAmount_Textfield = 'JavaWindow("title:=.* Fee .*").JavaEdit("attached text:=Requested Amount:")'
LIQ_Fee_FeeType_DropdownList = 'JavaWindow("title:=.* Fee .*").JavaList("attached text:=Fee Type:")'
LIQ_Fee_File_Save = 'JavaWindow("title:=.* Fee .*").JavaMenu("label:=File").JavaMenu("label:=Save")' 
LIQ_Fee_Window = 'JavaWindow("title:=.* Fee.*")'
LIQ_Fee_ArrangerFee_Window = 'JavaWindow("title:=.* Arranger Fee.*")'
LIQ_Fee_FeeType_DropdownList = 'JavaWindow("title:=.* Fee.*").JavaList("attached text:=Fee Type:")'
LIQ_Fee_File_Save = 'JavaWindow("title:=.* Fee.*").JavaMenu("label:=File").JavaMenu("label:=Save")' 

####Repayment Cashflows#####
LIQ_Repayment_Cashflows_Window = 'JavaWindow("title:=Cashflows .*")'
LIQ_Repayment_Cashflows_List  = 'JavaWindow("title:=Cashflows .*").JavaTree("attached text:=Drill down to view/change details")'
LIQ_Repayment_Cashflows_OK_Button = 'JavaWindow("title:=Cashflows .*").JavaButton("attached text:=OK")'
LIQ_Repayment_Cashflows_RemittanceDesc_None_StaticText = 'JavaWindow("title:=Cashflows .*").JavaStaticText("attached text:=None")'
LIQ_Repayment_Cashflows_RemittanceDesc_RTGS_StaticText = 'JavaWindow("title:=Cashflows .*").JavaStaticText("attached text:=.*RTGS.*")'
LIQ_Repayment_Cashflows_RemittanceDesc_IMT_StaticText = 'JavaWindow("title:=Cashflows .*").JavaStaticText("attached text:=.*IMT.*")'
LIQ_Repayment_Cashflows_DetailsforCashflow_Window = 'JavaWindow("title:=Details for Cashflow.*")'
LIQ_Repayment_Cashflows_DetailsforCashflow_SelectRI_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=Select Remittance Instructions")'
LIQ_Repayment_Cashflows_DetailsforCashflow_IMTDetail_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=IMT Detail")'
LIQ_Repayment_Cashflows_DetailsforCashflow_Exit_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=Exit")'
LIQ_Repayment_Cashflows_DetailsforCashflow_OK_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=OK")'
LIQ_Repayment_Cashflows_ChooseRemittance_Window = 'JavaWindow("title:=Choose Remittance Instructions")'
LIQ_Repayment_Cashflows_ChooseRemittance_List = 'JavaWindow("title:=Choose Remittance Instructions").JavaTree("attached text:=Drill down to view details")'
LIQ_Repayment_Cashflows_ChooseRemittance_OK_Button = 'JavaWindow("title:=Choose Remittance Instructions").JavaButton("attached text:=OK")'
LIQ_Repayment_Cashflows_SetToDoIt_Button = 'JavaWindow("title:=Cashflows .*").JavaButton("attached text:=Set Selected Item To.*Do It.*")'
LIQ_Repayment_Cashflows_SetUndoIt_Button = 'JavaWindow("title:=Cashflows .*").JavaButton("attached text:=Set Selected Item To.*Undo It.*")'
LIQ_Repayment_Cashflows_ViewOutgoingIMTMessages_Window = 'JavaWindow("title:=View Outgoing IMT Messages")'
LIQ_Repayment_Cashflows_ViewOutgoingIMTMessages_Cancel_Button = 'JavaWindow("title:=View Outgoing IMT Messages").JavaButton("attached text:=Cancel")'
LIQ_Repayment_Cashflows_MarkSelectedItemForRelease_Button = 'JavaWindow("title:=Cashflows .*").JavaButton("attached text:=Mark Selected Item For Release")'
LIQ_Repayment_Cashflows_HostBankCash_Workflow = 'JavaWindow("title:=Cashflows .*").JavaStaticText("to_class:=JavaStaticText","x:=270","y:=58")'

LIQ_Repayment_GLEntries_Table = 'JavaWindow("title:=GL Entries.*").JavaTree("attached text:=Drill down to view details")'
LIQ_Repayment_GLEntries_Window = 'JavaWindow("title:=GL Entries.*")'
LIQ_Repayment_Cashflows_Queries_GLEntries = 'JavaWindow("title:=Cashflows .*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Repayment_Cashflows_Options_MarkAllToRelease = 'JavaWindow("title:=Cashflows .*").JavaMenu("label:=Options").JavaMenu("label:=Mark All To Release")'

###NOTICES###
LIQ_Notice_PaperClipIntentNotice_Window = 'JavaWindow("title:=Paper Clip Intent Notice Group.*")'
LIQ_Notice_PaperClipIntentNotice_Exit_Button = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaButton("attached text:=Exit")' 
LIQ_Notice_PaperClipIntentNotice_Information_Table = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaTree("attached text:=Drill down to mark notices")'
LIQ_Notice_PaperClipIntentNotice_Send_Button = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaButton("attached text:=Send")'
LIQ_Notice_PaperClipIntentNotice_EditHighlightedNotice_Button = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaButton("attached text:=Edit Highlighted Notices")'

LIQ_Notice_PaperClipIntentNotice_Edit_Window = 'JavaWindow("title:=Paper Clip Intent Notice created.*")'
LIQ_Notice_PaperClipIntentNotice_Edit_Email = 'JavaWindow("title:=Paper Clip Intent Notice created.*").JavaEdit("attached text:=E-mail:")'
