## Main page
SSO_UserID_textfield = '//input[contains(@name,"userDetail:UserID")]'
SSO_Search_button = '//input[@name="Search"]'
SSO_GivenName_textfield = '//input[contains(@name,"userDetail:UserName")]'
SSO_Surname_textfield = '//input[contains(@name,"userDetail:Surname")]'
SSO_BusinessTitle_textfield = '//input[contains(@name,"userDetail:Title")]'
SSO_OSUserID_textfield = '//input[contains(@name,"userDetail:OSUserID")]'
SSO_UserCountryCode_dropdown = '//input[contains(@id,"CountryLocale")]'
SSO_UserType_dropdown = '//input[contains(@id,"UserType")]'
SSO_UserVarantLocale_textfield = '//input[contains(@name,"userDetail:VariantLocale")]'
SSO_UserLanguageCode_dropdown = '//input[contains(@id,"LanguageLocale")]'
SSO_RefUserInd_checkbox = '//input[contains(@id,"userDetail:ReferenceUser") and @type="checkbox"]'
SSO_RefUserID_textfield = '//input[contains(@id,"userDetail:ReferenceUser") and @type="text"]'
SSO_RefUserName_textfield = '//input[contains(@id,"ReferenceUserName") and @type="text"]'
SSO_UpdEntitlementofLinkedUsers_checkbox = '//input[contains(@name,"userDetail:RSAFlag") and @type="checkbox"]'
SSO_DFAAuthReq_checkbox = '//input[contains(@name,"userDetail:UpdateEntitlementOFLinkedUser") and @type="checkbox"]'
SSO_FingerprintAuthReqforReferrals_checkbox = '//input[contains(@name,"userDetail:FingerprintAuth") and @type="checkbox"]'
SSO_DefaultZone_dropdown = '//input[contains(@id,"userDetail:Zone") and @type="combo"]'
SSO_LinkedUserCount = '//input[contains(@name,"LinkedUserCount")]'
SSO_Email_textfield = '//input[contains(@name,"userDetail:Email")]'
SSO_Phone_textfield = '//input[contains(@name,"userDetail:Phone")]'
SSO_BranchSortCode_dropdown = '//input[contains(@id,"userDetail:BranchSortCode") and @type="combo"]'
SSO_AccBranch = '//input[contains(@id,"userDetail:BMBranch") and @type="combo"]'
SSO_AssocZones_tablegrid = '//div[contains(@id,"assignedZoneList")]//div[contains(@class,"GridView")]//div[@role="row"]'
SSO_AssocZones_tablegrid_values = '//td[@role="gridcell" and @idx="0"]'
SSO_AssocRoles_tablegrid = '//div[contains(@id,"assignedRoleList")]//div[contains(@class,"GridView")]//div[@role="row"]'
SSO_AssocRoles_tablegrid_values = '//td[@role="gridcell" and @idx="0"]'
SSO_AssocApps_tablegrid = '//div[contains(@id,"assignedAppList")]//div[contains(@class,"GridView")]//div[@role="row"]'
SSO_AssocApps_tablegrid_values = '//td[@role="gridcell" and @idx="0"]'
SSO_Next_button = '//input[@name="Next"]'


## Search User dialog
SSO_SearchUser_UserID_textfield = '//input[contains(@name,"userName")]'
SSO_SearchUser_Search_button = '//div[@role="dialog"]//input[@name="Search"]'
SSO_SearchUser_Clear_button = '//div[@role="dialog"]//input[@name="Clear"]'
SSO_SearchUser_Next_button = '//div[@role="dialog"]//input[@name="Next"]'
SSO_UserID_Row_table = '//div[contains(@class,"GridMasterView")]//div[contains(@id,"grid__View")]//tr'
SSO_Results_table = '//div[contains(@class,"GridMasterView")]//div[contains(@id,"grid__View")]//div[@role="row"]'
SSO_RadioButton_Col = '//td[@role="gridcell" and @idx="0"]/div[@role="radio"]'
SSO_UserID_Col = '//td[@role="gridcell" and @idx="1"]'
SSO_UserType = '//td[@role="gridcell" and @idx="2"]'
SSO_CountryCode = '//td[@role="gridcell" and @idx="3"]'
SSO_User_Not_Found_Label = '//div[@role="dialog"]//input[contains(@name,"msg")]'
SSO_Close_Dialog = '//span[@title="Cancel" and contains(@class,"DialogCloseIcon")]'
