###Create User###
Essence_CreateUser_UserId_TextBox = '//input[contains(@id,"UserDetail:UserID")]'
Essence_CreateUser_GivenName_TextBox = '//input[contains(@id,"UserDetail:UserName")]'
Essence_CreateUser_SurName_TextBox = '//input[contains(@id,"UserDetail:Surname")]'
Essence_CreateUser_BusinessTitle_TextBox = '//input[contains(@id,"UserDetail:Title")]'
Essence_CreateUser_OSUserID_TextBox = '//input[contains(@id,"UserDetail:OSUserID")]'
Essence_CreateUser_CountryCode_TextBox = '//input[contains(@id,"UserDetail:CountryLocale")]'
Essence_CreateUser_UserType_TextBox = '//input[contains(@id,"UserDetail:UserType")]'
Essence_CreateUser_LocalVariant_TextBox = '//input[contains(@id,"UserDetail:UserType")]'
Essence_CreateUser_LanguageCode_TextBox = '//input[contains(@id,"UserDetail:LanguageLocale")]'
Essence_CreateUser_Email_TextBox = '//input[contains(@id,"UserDetail:Email")]'
Essence_CreateUser_Phone_TextBox = '//input[contains(@id,"UserDetail:Phone")]'
Essence_CreateUser_DefaultZone_TextBox = '//input[contains(@id,"UserDetail:Zone")]'
Essence_CreateUser_BranchName_TextBox = '//input[contains(@id,"UserDetail:BranchSortCode")]'
Essence_CreateUser_LocalVariant_TextBox = '//input[contains(@id,"UserDetail:UserType")]'
Essence_CreateUser_Next_Button = '//input[contains(@id,"Next")]'
Essence_CreateUser_Message_Text = '//input[contains(@id,"ShowMessage")]'

Essence_CreateUser_Roles_Table = '//div[@role="presentation"]//div[contains(@id,"dojox_grid__View_3")]//div[@role="row"]'
Essence_CreateUser_RoleName_TableRow = '//td[@role="gridcell" and @idx="1"]'
Essence_CreateUser_Role_CheckBox = '//td[@role="gridcell" and @idx="0"]'
Essence_CreateUser_Role_SelectAll = '//div[@role="presentation"]//div[contains(@aria-label,"Select all")]'

###Amend User###
Essence_AmendUser_UserId_TextBox = '//input[contains(@id,"userDetail:UserID")]'
Essence_AmendUser_GivenName_TextBox = '//input[contains(@id,"userDetail:UserName")]'
Essence_AmendUser_SurName_TextBox = '//input[contains(@id,"userDetail:Surname")]'
Essence_AmendUser_BusinessTitle_TextBox = '//input[contains(@id,"userDetail:Title")]'
Essence_AmendUser_OSUserID_TextBox = '//input[contains(@id,"userDetail:OSUserID")]'
Essence_AmendUser_CountryCode_TextBox = '//input[contains(@id,"userDetail:CountryLocale")]'
Essence_AmendUser_UserType_TextBox = '//input[contains(@id,"userDetail:UserType")]'
Essence_AmendUser_LocalVariant_TextBox = '//input[contains(@id,"userDetail:UserType")]'
Essence_AmendUser_LanguageCode_TextBox = '//input[contains(@id,"userDetail:LanguageLocale")]'
Essence_AmendUser_Email_TextBox = '//input[contains(@id,"userDetail:Email")]'
Essence_AmendUser_Phone_TextBox = '//input[contains(@id,"userDetail:Phone")]'
Essence_AmendUser_DefaultZone_TextBox = '//input[contains(@id,"userDetail:Zone")]'
Essence_AmendUser_BranchName_TextBox = '//input[contains(@id,"userDetail:BranchSortCode")]'
Essence_AmendUser_LocalVariant_TextBox = '//input[contains(@id,"userDetail:UserType")]'
Essence_AmendUser_Next_Button = '//input[contains(@id,"Next")]'
Essence_AmendUser_Message_Text = '//input[contains(@id,"ShowMessage")]'