###Delete User###
Essence_DeleteUser_UserId_TextBox = '//input[contains(@name,"Username")]'
Essence_DeleteUser_Search_Button = '//input[contains(@name,"Search")]'
Essence_DeleteUser_Table = '//div[@role="presentation"]//div[contains(@id,"grid__View")]//div[@role="row"]'
Essence_DeleteUser_TableRow = '//div[@role="presentation"]//div[contains(@id,"grid__View")]//tr'
Essence_DeleteUser_UserId_TableCol = '//td[@role="gridcell" and @idx="1"]'
Essence_DeleteUser_CheckBox_TableCol = '//td[@role="gridcell" and @idx="0"]/div[@role="checkbox"]'
Essence_DeleteUser_Next_Button = '//input[contains(@name,"Next")]'
Essence_DeleteUser_Warning_Dialog = '//div[@role="dialog" and contains(@id,"EVENT_WARNING")]'
Essence_DeleteUser_WarningDialog_Proceed_Button = '//div[@class="ux-form-footerbuttons"]//input[contains(@id,"Proceed")]'
Essence_DeleteUser_WarningDialog_Message = '//textarea[contains(@name,"messages")]'
Essence_DeleteUser_Status_Form ='//form[@name="DeleteUser_SCF"]'
Essence_DeleteUser_Status_Message  = '//input[contains(@name,"ShowMessage")]'