###Main Page###
Essence_EnquireUser_UserID_TextBox = '//input[contains(@id,"userDetail:UserID")]'
Essence_EnquireUser_Search_Button = '//input[contains(@name,"Search")]'
Essence_EnquireUser_GivenName_TextBox = '//input[contains(@name,"userDetail:UserName")]'
Essence_EnquireUser_Surname_TextBox = '//input[contains(@name,"userDetail:Surname")]'
Essence_EnquireUser_Title_TextBox = '//input[contains(@name,"userDetail:Title")]'
Essence_EnquireUser_OSUserID_TextBox = '//input[contains(@name,"userDetail:OSUserID")]'
Essence_EnquireUser_Country_Dropdown = '//input[contains(@id,"userDetail:CountryLocale")]'
Essence_EnquireUser_UserType_Dropdown = '//input[contains(@id,"userDetail:UserType")]'
Essence_EnquireUser_Language_Dropdown = '//input[contains(@id,"userDetail:LanguageLocale")]'
Essence_EnquireUser_DefaultZone_Dropdown = '//input[contains(@id,"userDetail:Zone")]'
Essence_EnquireUser_BranchName_Dropdown = '//input[contains(@id,"userDetail:BranchSortCode")]'
Essence_EnquireUser_Phone_Dropdown = '//input[contains(@name,"userDetail:Phone")]'
Essence_EnquireUser_Email_Dropdown = '//input[contains(@name,"userDetail:Email")]'
Essence_EnquireUser_AssocZone_TableGrid_Row = '//div[contains(@id,"assignedZoneList")]//div[contains(@class,"GridView")]//div[@role="row"]'
TableGrid_RowValues_Zone = '//td[@role="gridcell" and @idx="0"]'
TableGrid_RowValues_Branch = '//td[@role="gridcell" and @idx="1"]'
Essence_EnquireUser_AssocRoles_TableGrid_Row = '//div[contains(@id,"assignedRoleList")]//div[contains(@class,"GridView")]//div[@role="row"]'
TableGrid_RowValues_Role = '//td[@role="gridcell" and @idx="0"]'
Essence_HelpMenu_Button  =   '//span[@widgetid="uxpHelpMenu"]//span[@class="dijitReset dijitInline dijitArrowButtonInner"]'
Essence_LogOut_Button  =   '//div[@aria-label="uxpUserHelpList"]//tr[@widgetid="logoutButton"]'

###Search User dialog###
Essence_SearchUser_UserID_TextBox = '//td[@class="ux-layoutContainer"]//input[contains(@name,"userName")]'
Essence_SearchUser_Search_Button = '//span[text()="Search User"]//parent::div//following::div//input[contains(@name,"Search")]'
Essence_SearchUser_Next_Button = '//div[@role="dialog"]//input[contains(@name,"Next")]'
Essence_SearchUser_Table = '//div[@role="dialog"]//div[contains(@id,"grid__View")]//div[@role="row"]'
Essence_SearchUser_TableRow = '//div[@role="dialog"]//div[contains(@id,"grid__View")]//tr'
Essence_SearchUser_UserType_TableRow = '//td[@role="gridcell" and @idx="2"]'
Essence_SearchUser_UserCountry_TableRow = '//td[@role="gridcell" and @idx="3"]'
Essence_SearchUser_UserID_TableRow = '//td[@role="gridcell" and @idx="1"]'
Essence_SearchUser_RadioButton_Col = '//td[@role="gridcell" and @idx="0"]/div[@role="radio"]'
Essence_SearchUser_Error_TextMessage = '//div[@role="dialog"]//input[@uitype="ValueLabel" and contains(@name,"msg")]'
Essence_SearchUser_Close_Dialog = '//span[@title="Cancel" and contains(@class,"DialogCloseIcon")]'
